import {
  AgentApplication,
  CardFactory,
  MemoryStorage,
  TurnState
} from '@microsoft/agents-hosting'
import { ConversationMemory, Orchestrator } from './orchestrator.js'

interface ConversationState {
  memory?: ConversationMemory
}

export type AppState = TurnState<ConversationState>

const WELCOME =
  "👋 I'm **Decision Memory** — your organization's institutional memory for decisions.\n\n" +
  'Try asking:\n' +
  '- *Why did we choose PostgreSQL?*\n' +
  "- *We're proposing to use MongoDB for the orders service* (I'll check for conflicts)\n" +
  '- *What is our current standard for partner APIs?*\n' +
  '- *Record a decision: ...*'

export function buildAgentApp(orchestrator: Orchestrator): AgentApplication<AppState> {
  const app = new AgentApplication<AppState>({
    storage: new MemoryStorage(),
    // Disable typing timer; streaming handles UX feedback
    startTypingTimer: false,
    // Strip "@Decision Memory" from group-chat/Copilot messages so the
    // orchestrator sees only the user's actual text.
    removeRecipientMention: true,
    normalizeMentions: true
  })

  // Persist conversation memory between turns for confirmation workflow
  app.onTurn('afterTurn', async () => true)

  app.onConversationUpdate('membersAdded', async (context) => {
    // Greet when a user joins; in Teams the bot's own install also raises
    // membersAdded, which would double-send the welcome.
    const botId = context.activity.recipient?.id
    const added = context.activity.membersAdded ?? []
    if (added.some((member) => member.id && member.id !== botId)) {
      await context.sendActivity(WELCOME)
    }
  })

  app.onActivity('message', async (context, state) => {
    const text = context.activity.text?.trim() ?? ''
    if (!text) return

    // Stream response for faster feedback; non-streaming channels fallback to a single message
    const stream = context.streamingResponse
    stream.setGeneratedByAILabel(true) // "Generated by AI" label on the final message

    try {
      stream.queueInformativeUpdate('Searching the decision records…')

      const memory: ConversationMemory = state.conversation.memory ?? {}
      const result = await orchestrator.run(text, memory)
      state.conversation.memory = memory

      const safeText =
        result.text?.trim() ||
        'I found relevant decision data, but could not format the final response text. Please try again.'

      // Render Adaptive Cards only on channels that support them (emulator/webchat/directline/test);
      // others receive Markdown to avoid flattened/broken formatting
      const channelId = (context.activity.channelId ?? '').toLowerCase()
      const CARD_RENDERING_CHANNELS = new Set(['emulator', 'webchat', 'directline', 'test'])
      const cardsRenderInline = CARD_RENDERING_CHANNELS.has(channelId)
      console.log(
        `Reply surface: channelId="${channelId || '(none)'}" -> ${cardsRenderInline ? 'adaptive cards' : 'markdown'}`
      )

      if (cardsRenderInline && result.cards.length > 0) {
        stream.queueTextChunk(safeText)
        stream.setAttachments(result.cards.map((card) => CardFactory.adaptiveCard(card)))
      } else if (result.markdown) {
        stream.queueTextChunk(`${safeText}\n\n${result.markdown}`)
      } else {
        stream.queueTextChunk(safeText)
      }

      await stream.endStream()
    } catch (err) {
      // Surface a friendly reply instead of Teams/Copilot's generic
      // "something went wrong" when a turn fails.
      console.error('Turn failed:', err)
      const message =
        'Sorry — I hit an internal error processing that. Please try again; if it persists, check the agent logs.'
      try {
        stream.queueTextChunk(message)
        await stream.endStream()
      } catch {
        // Stream already ended/canceled — fall back to a normal message.
        await context.sendActivity(message)
      }
    }
  })

  return app
}
