import {
  AgentApplication,
  CardFactory,
  MemoryStorage,
  TurnState
} from '@microsoft/agents-hosting'
import { ConversationMemory, Orchestrator } from './orchestrator.js'

interface ConversationState {
  memory?: ConversationMemory
}

export type AppState = TurnState<ConversationState>

const WELCOME =
  "👋 I'm **Decision Memory** — your organization's institutional memory for decisions.\n\n" +
  'Try asking:\n' +
  '- *Why did we choose PostgreSQL?*\n' +
  "- *We're proposing to use MongoDB for the orders service* (I'll check for conflicts)\n" +
  '- *What is our current standard for partner APIs?*\n' +
  '- *Record a decision: ...*'

export function buildAgentApp(orchestrator: Orchestrator): AgentApplication<AppState> {
  const app = new AgentApplication<AppState>({
    storage: new MemoryStorage(),
    // Responses are streamed (see the message handler). Streaming emits its own
    // "thinking" informative updates, so the built-in typing timer is disabled
    // to avoid competing typing activities that disrupt the stream sequence.
    startTypingTimer: false,
    // Strip "@Decision Memory" from group-chat/Copilot messages so the
    // orchestrator sees only the user's actual text.
    removeRecipientMention: true,
    normalizeMentions: true
  })

  // The SDK only persists turn state when an afterTurn handler is registered
  // (state.save runs inside that block), and the confirm-before-write flow
  // depends on conversation state surviving between turns.
  app.onTurn('afterTurn', async () => true)

  app.onConversationUpdate('membersAdded', async (context) => {
    // Greet when a user joins; in Teams the bot's own install also raises
    // membersAdded, which would double-send the welcome.
    const botId = context.activity.recipient?.id
    const added = context.activity.membersAdded ?? []
    if (added.some((member) => member.id && member.id !== botId)) {
      await context.sendActivity(WELCOME)
    }
  })

  app.onActivity('message', async (context, state) => {
    const text = context.activity.text?.trim() ?? ''
    if (!text) return

    // Stream the response. On Copilot Chat and Teams the orchestrator's
    // multi-step LLM + tool loop often takes longer than Copilot's synchronous
    // reply window; opening a stream with an early informative update keeps the
    // turn alive so Copilot waits for the answer instead of showing "I'll keep
    // working… respond later" and dropping the reply that lands moments later.
    // On non-streaming channels (playground / ExpectReplies) this degrades to a
    // single final message.
    const stream = context.streamingResponse
    stream.setGeneratedByAILabel(true) // "Generated by AI" label on the final message

    try {
      stream.queueInformativeUpdate('Searching the decision records…')

      const memory: ConversationMemory = state.conversation.memory ?? {}
      const result = await orchestrator.run(text, memory)
      state.conversation.memory = memory

      const safeText =
        result.text?.trim() ||
        'I found relevant decision data, but could not format the final response text. Please try again.'

      // M365 Copilot flattens Adaptive Card attachments from custom engine agents
      // into raw text: inline markdown is left literal (**bold**) and the
      // TextBlocks run together with no layout. Only a few channels actually
      // render card attachments well — the Agents Playground ("emulator") and
      // Web Chat / Direct Line. Everything else (Teams/Copilot "msteams", and any
      // unrecognized channel) gets the same detail as Markdown in the message
      // text, which renders cleanly — mirroring the official PnP custom-engine
      // agent samples that reply with Markdown instead of card attachments. Using
      // an allow-list (not "everything except msteams") means an unexpected
      // Copilot channelId still falls back to Markdown rather than a broken card.
      const channelId = (context.activity.channelId ?? '').toLowerCase()
      const CARD_RENDERING_CHANNELS = new Set(['emulator', 'webchat', 'directline', 'test'])
      const cardsRenderInline = CARD_RENDERING_CHANNELS.has(channelId)
      console.log(
        `Reply surface: channelId="${channelId || '(none)'}" -> ${cardsRenderInline ? 'adaptive cards' : 'markdown'}`
      )

      if (cardsRenderInline && result.cards.length > 0) {
        stream.queueTextChunk(safeText)
        stream.setAttachments(result.cards.map((card) => CardFactory.adaptiveCard(card)))
      } else if (result.markdown) {
        stream.queueTextChunk(`${safeText}\n\n${result.markdown}`)
      } else {
        stream.queueTextChunk(safeText)
      }

      await stream.endStream()
    } catch (err) {
      // Surface a friendly reply instead of Teams/Copilot's generic
      // "something went wrong" when a turn fails.
      console.error('Turn failed:', err)
      const message =
        'Sorry — I hit an internal error processing that. Please try again; if it persists, check the agent logs.'
      try {
        stream.queueTextChunk(message)
        await stream.endStream()
      } catch {
        // Stream already ended/canceled — fall back to a normal message.
        await context.sendActivity(message)
      }
    }
  })

  return app
}
